version: '3.5'

services:
  annea_baz:
    image: annea_baz
    build:
      context: .
      dockerfile: apps/annea_baz/Dockerfile
    container_name: annea_baz
    volumes:
      - "./apps/annea_baz:/apps/annea_baz"
