version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install tox
            (cd libs/annea_foo; tox)
            (cd libs/annea_bar; tox)
            (cd apps/annea_baz; tox)
  build-and-push-docker:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/python-framework
    steps:
      - checkout:
          path: ~/python-framework
      - run: docker login --username $DOCKER_USER --password $DOCKER_PASS
      - run: docker build -t anneaai/baz:$CIRCLE_BUILD_NUM -f apps/annea_baz/Dockerfile .
      - run: docker push anneaai/baz:$CIRCLE_BUILD_NUM
      - run: docker tag anneaai/baz:$CIRCLE_BUILD_NUM anneaai/baz:latest
      - run: docker push anneaai/baz:latest
workflows:
  build-and-release:
    jobs:
      - test
      - build-and-push-docker:
          requires:
            - test