version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install tox
            (cd libs/annea_foo; tox)
            (cd libs/annea_bar; tox)
            (cd apps/baz; tox)
workflows:
  build:
    jobs:
      - build-and-test

