version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install tox
            (cd libs/annea_foo; tox)
            (cd libs/annea_bar; tox)
            (cd apps/baz; tox)
  pypi-publish:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install twine
            (cd libs/annea_bar; python setup.py bdist_wheel; twine upload dist/*)
            (cd libs/annea_foo; python setup.py bdist_wheel; twine upload dist/*)
  build-and-push-docker:
    machine: true
    steps:
      - checkout
      - run: docker login --username $DOCKER_USER --password $DOCKER_PASS
      - run: cd apps/baz
      - run: docker build -t anneaai/baz:$CIRCLE_BUILD_NUM .
      - run: docker tag anneaai/baz:$BITBUCKET_BUILD_NUM anneaai/baz:latest
      - run: docker push anneaai/baz:$BITBUCKET_BUILD_NUM
workflows:
  build-test-and-approval-deploy:
    jobs:
      - build-and-test
      - hold1:
          type: approval
          requires:
            - build-and-test
      - pypi-publish:
          requires:
            - hold1
      - hold2:
          type: approval
          requires:
            - build-and-test
      - build-and-push-docker:
          requires:
            - hold2