version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install tox
            (cd libs/annea_foo; tox)
            (cd libs/annea_bar; tox)
            (cd apps/baz; tox)
  pypi-publish:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install twine
            (cd libs/annea_bar; python setup.py bdist_wheel; twine upload dist/*)
            (cd libs/annea_foo; python setup.py bdist_wheel; twine upload dist/*)
  build-and-push-docker:
    machine: true
    working_directory: ~/python-framework/apps/baz
    steps:
      - checkout:
          path: ~/python-framework
      - run: docker login --username $DOCKER_USER --password $DOCKER_PASS
      - run: docker build -t anneaai/baz:$CIRCLE_BUILD_NUM .
      - run: docker push anneaai/baz:$CIRCLE_BUILD_NUM
      - run: docker tag anneaai/baz:$CIRCLE_BUILD_NUM anneaai/baz:latest
      - run: docker push anneaai/baz:latest
workflows:
  build_and_test:
    jobs:
      - build-and-test:
        filters:
          tags:
            ignore: /^v.*/
  build_and_release:
    jobs:
      - build-and-test:
        filters:
          tags:
            only: /.*/
      - pypi-publish:
          filters:
            tags:
              only: pypi
          requires:
            - build-and-test
      - build-and-push-docker:
          filters:
            tags:
              only: docker
          requires:
            - build-and-test